server:
  port: 8003
spring:
  application:
    name: user-item-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka
ribbon:
  eureka:
    enabled: true